#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "feature/**" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fondamentale per Qodana per calcolare la cronologia dei passati commit

      - name: Set up JDK 21 (For Maven dependencies caching)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # Riduce drasticamente il tempo di esecuzione di Qodana scaricando le dipendenze dalla cache

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # Attiva il pr-mode (analisi parziale) se è una PR OPPURE se stai pushando su un branch di feature
          pr-mode: ${{ github.event_name == 'pull_request' || contains(github.ref, 'refs/heads/feature/') }}
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: true
          push-fixes: 'none'